name: CareerCrush CD/CI

on:
  push:
    bracnhes:
      -"main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: {18.x}
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm rund build
      - run: npm test
          