name: CareerCrush CD/CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      # Check if build directory exists
      - name: Check if build directory exists
        run: |
          if [ -d "build" ]; then
            echo "Build directory exists."
            exit 0  # Exit with success code if directory exists
          else
            echo "Build directory not found."
            exit 1  # Exit with error code if directory does not exist
          fi
        continue-on-error: true

      # Upload to S3 if the "build" directory exists
      - name: Upload to S3
        if: ${{ success() }}
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: "build"
